# Generated by Django 3.1.6 on 2021-03-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addtocart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='image_url',
            field=models.ImageField(upload_to='none'),
        ),
    ]
