# Generated by Django 3.1.6 on 2021-03-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addtocart', '0002_auto_20210302_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='image_url',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
