# Generated by Django 3.1.6 on 2021-03-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('image_url', models.ImageField(upload_to='')),
                ('url_description', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
